### ISSUE TITLE
Image information when training the text encoder for COCO?

### ISSUE THREAD

**Issue by jiasenlu** [reedscot/icml2016#12]
Hi Reed

This is really a nice work and thanks for sharing the code. 

However, when I trying to read the code for text encoder for COCO, it seems your loss function is just using the text information. there is no image information used here. However, things are different for flower and bird dataset. 

https://github.com/reedscot/icml2016/blob/master/main_txt_coco.lua#L138

Could you give some hint why you did this? 

Thanks

Best

Jiasen

**Comment by reedscot** [comment]
Thanks! Actually I think using both image and text information to train the
COCO encoder should work fine as well, but it would probably be a bit
slower and require extracting or loading pre-extracted image features.

**Comment by jiasenlu** [comment]
I see. Thanks for your quick reply! I wonder do you think training the text encoder together with the GAN together will also work here? or it will be too hard to optimize?
